export { default as NotFound } from './NotFound'
export { default as Home } from './Home'
export { default as Detail } from './Detail'
export { default as Contact } from './Contact'
export { default as News } from './News'
